"""Add photo_url to missing_persons

Revision ID: 379bf463965d
Revises: 
Create Date: 2025-11-16 23:15:43.616041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '379bf463965d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('missing_person')
    with op.batch_alter_table('missing_persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missing_persons', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    op.create_table('missing_person',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_seen_location', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('last_seen_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('photo_url', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='missing_person_pkey')
    )
    # ### end Alembic commands ###
